<a href="https://colab.research.google.com/github/parimalrajsscet/DemoSamples/blob/master/Encoder_Decoder.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Seq2Seq problems

# the input and output both are sequences

# 1. translation ( eng- spanish, eng-hindi)
# 2. text summarization
# 3. chatbot conversation
# 4. image to text generation
# 5. speech recognition
# 6. text to image
# 7. transcription



# In all these problems the input and output sequence length can be different
# Therefore the RNN and LSTM models will be able to do the task but not that efficiently.

In [ ]:
# Encoder - Decoder

# break the task into two parts and therefore increases the efficiency as well

# just like you doing one task is goiing to be maybe 50% efficient
# but if your friend joins you along in the task the efficiency can be 80%

## import the lib

In [ ]:
import numpy as np
import tensorflow as tf

In [ ]:
data = [ ("i am happy","मैं खुश हूँ"),
         ("You are sad","आप दुखी हैं"),
         ("she is tired", "वह थक गया है"),
         ("we are hungry","हम भूखें है"),
         ("they are busy","वे व्यस्त हैं"),
         ("i am cold","मुझे ठंड लग रही है"),
         ("you are late","तुम देरी से आए हो"),
         ("she is happy", "वह खुश है"),
         ("we are ready","हम तैयार हैं")]

In [ ]:
eng_sen =[]
hin_sen = []

for sen in data:
  eng_sen.append(sen[0])
  hin_sen.append(sen[1])

In [ ]:
eng_sen

['i am happy',
 'You are sad',
 'she is tired',
 'we are hungry',
 'they are busy',
 'i am cold',
 'you are late',
 'she is happy',
 'we are ready']

In [ ]:
hin_sen

['मैं खुश हूँ',
 'आप दुखी हैं',
 'वह थक गया है',
 'हम भूखें है',
 'वे व्यस्त हैं',
 'मुझे ठंड लग रही है',
 'तुम देरी से आए हो',
 'वह खुश है',
 'हम तैयार हैं']

## Add \<start> and \<end>

In [ ]:
hin_sen = ['<start>'+sen+"<end>" for sen in hin_sen]

In [ ]:
hin_sen

['<start>मैं खुश हूँ<end>',
 '<start>आप दुखी हैं<end>',
 '<start>वह थक गया है<end>',
 '<start>हम भूखें है<end>',
 '<start>वे व्यस्त हैं<end>',
 '<start>मुझे ठंड लग रही है<end>',
 '<start>तुम देरी से आए हो<end>',
 '<start>वह खुश है<end>',
 '<start>हम तैयार हैं<end>']

## Tokenisation

In [ ]:
from tensorflow.keras.preprocessing.text import Tokenizer

In [ ]:
eng_tokenizer = Tokenizer()
hin_tokenizer = Tokenizer()

In [ ]:
eng_tokenizer.fit_on_texts(eng_sen)
hin_tokenizer.fit_on_texts(hin_sen)

In [ ]:
eng_seq = eng_tokenizer.texts_to_sequences(eng_sen)
hin_seq = hin_tokenizer.texts_to_sequences(hin_sen)

In [ ]:
eng_seq

[[2, 3, 4],
 [5, 1, 9],
 [6, 7, 10],
 [8, 1, 11],
 [12, 1, 13],
 [2, 3, 14],
 [5, 1, 15],
 [6, 7, 4],
 [8, 1, 16]]

In [ ]:
hin_seq

[[1, 8, 5, 9, 2],
 [1, 10, 11, 4, 2],
 [1, 6, 12, 13, 3, 2],
 [1, 7, 14, 3, 2],
 [1, 15, 16, 4, 2],
 [1, 17, 18, 19, 20, 3, 2],
 [1, 21, 22, 23, 24, 25, 2],
 [1, 6, 5, 3, 2],
 [1, 7, 26, 4, 2]]

In [ ]:
print(eng_tokenizer.word_index)

{'are': 1, 'i': 2, 'am': 3, 'happy': 4, 'you': 5, 'she': 6, 'is': 7, 'we': 8, 'sad': 9, 'tired': 10, 'hungry': 11, 'they': 12, 'busy': 13, 'cold': 14, 'late': 15, 'ready': 16}


In [ ]:
print(hin_tokenizer.word_index)

{'start': 1, 'end': 2, 'है': 3, 'हैं': 4, 'खुश': 5, 'वह': 6, 'हम': 7, 'मैं': 8, 'हूँ': 9, 'आप': 10, 'दुखी': 11, 'थक': 12, 'गया': 13, 'भूखें': 14, 'वे': 15, 'व्यस्त': 16, 'मुझे': 17, 'ठंड': 18, 'लग': 19, 'रही': 20, 'तुम': 21, 'देरी': 22, 'से': 23, 'आए': 24, 'हो': 25, 'तैयार': 26}


In [ ]:
print(eng_tokenizer.word_counts)

OrderedDict({'i': 2, 'am': 2, 'happy': 2, 'you': 2, 'are': 5, 'sad': 1, 'she': 2, 'is': 2, 'tired': 1, 'we': 2, 'hungry': 1, 'they': 1, 'busy': 1, 'cold': 1, 'late': 1, 'ready': 1})


In [ ]:
print(hin_tokenizer.word_counts)

OrderedDict({'start': 9, 'मैं': 1, 'खुश': 2, 'हूँ': 1, 'end': 9, 'आप': 1, 'दुखी': 1, 'हैं': 3, 'वह': 2, 'थक': 1, 'गया': 1, 'है': 4, 'हम': 2, 'भूखें': 1, 'वे': 1, 'व्यस्त': 1, 'मुझे': 1, 'ठंड': 1, 'लग': 1, 'रही': 1, 'तुम': 1, 'देरी': 1, 'से': 1, 'आए': 1, 'हो': 1, 'तैयार': 1})


In [ ]:
eng_vocab_size = len(eng_tokenizer.word_index) + 1
hin_vocab_size = len(hin_tokenizer.word_index) + 1

In [ ]:
eng_vocab_size

17

In [ ]:
hin_vocab_size

27

## Padding

In [ ]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [ ]:
eng_padded = pad_sequences(eng_seq, padding = 'post')
hin_padded = pad_sequences(hin_seq, padding = 'post')

In [ ]:
print(eng_padded)
print("*"*30)
print(hin_padded)

[[ 2  3  4]
 [ 5  1  9]
 [ 6  7 10]
 [ 8  1 11]
 [12  1 13]
 [ 2  3 14]
 [ 5  1 15]
 [ 6  7  4]
 [ 8  1 16]]
******************************
[[ 1  8  5  9  2  0  0]
 [ 1 10 11  4  2  0  0]
 [ 1  6 12 13  3  2  0]
 [ 1  7 14  3  2  0  0]
 [ 1 15 16  4  2  0  0]
 [ 1 17 18 19 20  3  2]
 [ 1 21 22 23 24 25  2]
 [ 1  6  5  3  2  0  0]
 [ 1  7 26  4  2  0  0]]


In [ ]:
max_eng_len = eng_padded.shape[1]
max_hin_len = hin_padded.shape[1]

In [ ]:
print(max_eng_len, max_hin_len)

3 7


In [ ]:
eng_padded = pad_sequences(eng_seq, maxlen= max_hin_len, padding = 'post')

In [ ]:
eng_padded

array([[ 2,  3,  4,  0,  0,  0,  0],
       [ 5,  1,  9,  0,  0,  0,  0],
       [ 6,  7, 10,  0,  0,  0,  0],
       [ 8,  1, 11,  0,  0,  0,  0],
       [12,  1, 13,  0,  0,  0,  0],
       [ 2,  3, 14,  0,  0,  0,  0],
       [ 5,  1, 15,  0,  0,  0,  0],
       [ 6,  7,  4,  0,  0,  0,  0],
       [ 8,  1, 16,  0,  0,  0,  0]], dtype=int32)

## RNN

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, SimpleRNN, Dense

In [ ]:
model = Sequential()

model.add(Embedding(input_dim = eng_vocab_size,
                    output_dim = 64,
                    input_length = max_eng_len ))

model.add(SimpleRNN(64, return_sequences=True))

model.add(Dense(hin_vocab_size, activation = 'softmax'))

model.compile(optimizer = 'adam',
              loss = 'sparse_categorical_crossentropy',
              metrics=['accuracy'])

# hin_padded = np.expand_dims(hin_padded, -1)

model.build(input_shape=(None,max_eng_len))
model.summary()

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)         │ (None, 3, 64)          │         1,088 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn_2 (SimpleRNN)        │ (None, 3, 64)          │         8,256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 3, 27)          │         1,755 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 11,099 (43.36 KB)

 Trainable params: 11,099 (43.36 KB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
eng_padded.shape

(9, 3)

In [ ]:
hin_padded.shape

(9, 7)

In [ ]:
model.fit(eng_padded, hin_padded,
          epochs = 100,
          batch_size=2)

Epoch 1/100


ValueError: Arguments `target` and `output` must have the same shape up until the last dimension: target.shape=(None, 7), output.shape=(None, 3, 27)

In [ ]:
model.fit(eng_padded, hin_padded,
          epochs = 100,
          batch_size=2)

Epoch 1/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.0000e+00 - loss: 3.3069
Epoch 2/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.2857 - loss: 3.1920
Epoch 3/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.4444 - loss: 3.0545 
Epoch 4/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.4603 - loss: 2.8481
Epoch 5/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.4921 - loss: 2.6360 
Epoch 6/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4921 - loss: 2.4451
Epoch 7/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.4921 - loss: 2.3308 
Epoch 8/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.5079 - loss: 2.2592
Epoch 9/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.5397 - loss: 2.1805
Epoch 10/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.5714 - loss: 2.1081
Epoch 11/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6349 - loss: 2.0345
Epoch 12/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6349 

In [ ]:
pred = model.predict(eng_padded)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 309ms/step


In [ ]:
pred_seq = np.argmax(pred, axis = -1)
print(pred_seq)

[[ 1 17  5  9  2  0  0]
 [ 1 10 11  4  2  0  0]
 [ 1  6 12 13  3  2  0]
 [ 1  7 14  3  2  0  0]
 [ 1 15 16  4  2  0  0]
 [ 1 17 18 19 20  3  2]
 [ 1 10 22 23 24 25  2]
 [ 1  6  5  3  2  0  0]
 [ 1  7 26  4  2  0  0]]


In [ ]:
for seq in pred_seq:
  sentence = []
  for idx in seq:
    if idx != 0:
      word = hin_tokenizer.index_word.get(idx, " ")
      sentence.append(word)
  print(" ".join(sentence))

start मुझे खुश हूँ end
start आप दुखी हैं end
start वह थक गया है end
start हम भूखें है end
start वे व्यस्त हैं end
start मुझे ठंड लग रही है end
start आप देरी से आए हो end
start वह खुश है end
start हम तैयार हैं end


#Encoder - Decoder

In [ ]:
# Teacher Forcing

# we give correct previous word model predict next word

In [ ]:
decoder_input = hin_padded[:,:-1]
decoder_output = hin_padded[:, 1:]


print(decoder_input)
print("*"*20)
print(decoder_output)

[[ 1  8  5  9  2  0]
 [ 1 10 11  4  2  0]
 [ 1  6 12 13  3  2]
 [ 1  7 14  3  2  0]
 [ 1 15 16  4  2  0]
 [ 1 17 18 19 20  3]
 [ 1 21 22 23 24 25]
 [ 1  6  5  3  2  0]
 [ 1  7 26  4  2  0]]
********************
[[ 8  5  9  2  0  0]
 [10 11  4  2  0  0]
 [ 6 12 13  3  2  0]
 [ 7 14  3  2  0  0]
 [15 16  4  2  0  0]
 [17 18 19 20  3  2]
 [21 22 23 24 25  2]
 [ 6  5  3  2  0  0]
 [ 7 26  4  2  0  0]]
